### ISSUE TITLE
Infinit loop execution in usp_jobQueueGetStatus

### ISSUE THREAD

**Issue by razvantim** [rentadba/dbaTDPMon#1]
From time to time, the stored procedure usp_jobQueueGetStatus runs into infinite loop

By removing the comment from above, it fixes the problem

https://github.com/rentadba/dbaTDPMon/blob/7bb3450ffbd6eebd88b93343076b119892d106d6/source/common/stored-procedures/dbo.usp_jobQueueGetStatus.sql#L156

This is caused by jobs in the queue having status 4 and agent jobs not being available in SQL agent

**Comment by rentadba** [comment]
The bug was fixed: https://github.com/rentadba/dbaTDPMon/commit/e4e28d0e0ac9cbfaa5c8361152fa7f1da96370c9
Thank you Razvan for finding and reporting it. 
Cheers
